module.exports = function(){
	return {
		products: [
			{id: 1, title: "Misadventures of a Common Box Turtle", category: "Fiction",
			length: 10, price: 2.00, image: "../../assets/F_10.png"},
			{id: 2, title: "A Day in the Life of Abraham Lincoln", category: "Non-Fiction",
			length: 15, price: 3, image: "../../assets/NF_15.png"},
			{id: 3, title: "A Good Deed", category: "Fiction",
			length: 5, price: 1, image: "../../assets/F_5.png"},
			{id: 4, title: "Arsonists Dream", category: "Fiction",
			length: 10, price: 2, image: "../../assets/F_10.png"},
			{id: 5, title: "Library of Congress", category: "Non-Fiction",
			length: 15, price: 3, image: "../../assets/NF_5.png"},
			{id: 6, title: "Almost Conquered the World", category: "Fiction",
			length: 5, price: 1, image: "../../assets/F_5.png"},
			{id: 7, title: "Everywhere We Walked", category: "Fiction",
			length: 5, price: 1, image: "../../assets/F_5.png"},
			{id: 8, title: "Famous Patina", category: "Non-Fiction",
			length: 5, price: 1, image: "../../assets/NF_5.png"},
			{id: 9, title: "Frostbite", category: "Non-Fiction",
			length: 15, price: 3, image: "../../assets/NF_15.png"},
			{id: 10, title: "Old Ironsides", category: "Non-Fiction",
			length: 10, price: 2, image: "../../assets/NF_10.png"},
			{id: 11, title: "An Old, Fat Cat", category: "Fiction",
			length: 5, price: 1, image: "../../assets/F_5.png"},
			{id: 12, title: "Buffalo Brothers", category: "Fiction",
			length: 10, price: 2, image: "../../assets/F_10.png"},
			{id: 13, title: "Save the Date", category: "Fiction",
			length: 10, price: 2, image: "../../assets/F_10.png"},
			{id: 14, title: "Secret Treasures", category: "Fiction",
			length: 5, price: 1, image: "../../assets/F_5.png"},
			{id: 15, title: "The First Ladies Cat", category: "Non-Fiction",
			length: 10, price: 2, image: "../../assets/NF_10.png"},
			{id: 16, title: "Mining for Diamonds", category: "Non-Fiction",
			length: 15, price: 3, image: "../../assets/NF_15.png"},
			{id: 17, title: "Ancient Runes", category: "Non-Fiction",
			length: 5, price: 1, image: "../../assets/NF_5.png"},
			{id: 18, title: "Monstrous Children", category: "Fiction",
			length: 15, price: 3, image: "../../assets/F_15.png"},
			{id: 19, title: "Lily in the Pond", category: "Fiction",
			length: 10, price: 2, image: "../../assets/F_10.png"},
			{id: 20, title: "The Ex", category: "Fiction",
			length: 5, price: 1, image: "../../assets/F_5.png"}
		],
		orders:[]
	}
}